eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
server:
  port: 9001
spring:
  main:
    allow-circular-references: true
  application:
    name: spring-cloud-consumer
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
      eager: true