eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9000
spring:
  main:
    allow-circular-references: true
  application:
    name: spring-cloud-producer
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
      eager: true